config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'


  resources :articles
  resources :pages
  resources :contact


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  end
  # Defines the root path route ("/")
  # root "posts#index"

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @article = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article  = Article.new

  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to articles_path, notice: "Article Saved!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to articles_path, notice: "Article Changed!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path, notice: "Article deleted successfully."
  end

private
  def article_params
    params.require(:article).permit(:title, :body)
  end


end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def index
    @contact = Contact.all
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)

    if @contact.save
      redirect_to contact_path, notice: "Contact Incoming!"
    else
      render :new, status: :unprocessable_entity
    end
  end


  private
  def contact_params
    params.require(:contact).permit(:first_name, :last_name, :email, :comment)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_cancel.html.erb
<%= button_to "Cancel", articles_path %>

app/views/articles/_delete.html.erb
<%= button_to "Delete", article_path(@article), class: 'btn', method: :delete, data: { confirm: "Are you sure?" } %>

app/views/articles/_form.html.erb
<section class="articles-main">
<%= form_with model: article || Article.new do |form| %>
    <div>
        <%= form.label :title %><br>
        <%= form.text_field :title %><br>
        <% @article.errors.full_messages_for(:title).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>
    <div>
        <%= form.label :body %><br>
        <%= form.text_area :body, size: "40x10" %><br>
        <% @article.errors.full_messages_for(:body).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>
    <div >
        <%= form.submit 'Submit', class: 'btn' %>
        <% if @article.persisted?%>
            <%= render "delete", article: @article%>
        <% end %>
        <%= link_to "Cancel", articles_path, method: :get, class: 'btn ' %>
        
    </div>
<% end %>
</section>

app/views/articles/edit.html.erb
<h1>Edit</h1>
<div class="input">
<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <%= stylesheet_link_tag "application" %>
    </head>
    <body>
    <div class="articles-container">
    <h1>Articles</h1>
    <p>Find me in app/views/articles/index.html.erb</p>
    <section class= "articles-main">

        <ul>
            <% @article.each do |article| %>
            <div class="article-card">
                <li>
                    <h3><%= article.title %></h3><br>
                    <div class="article-body">
                    <%= article.body %>
                    <%= link_to "Edit", edit_article_path(article) %>
                    </div>
                </li>
            </div>
            <% end %>
        </ul>
    </section>
    </div>
    <div class="article-links">
        <%= link_to "New Article", new_article_path%>

        <%= link_to "Home", pages_path %>
    </div>
        
        <script src="" async defer></script>
    </body>
</html>

app/views/articles/list.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>This is the show html.erb</p>


</body>
</html>

app/views/articles/new.html.erb
    <body>
        <%= render "form", article: @article%>

        <script src="" async defer></script>
    </body>
</html> 

app/views/articles/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>This is the show html.erb</p>


</body>
</html>  

app/views/contact/new.html.erb
<body>
<h1> Hello! </h1>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Article Area</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <header>
    <i class='bx bx-book-content'></i>
    <div class= header-links>
      <li>
        <%= link_to "Home", pages_path %>
      </li>
      <li>
        <%= link_to "Articles", articles_path %>
      </li>
      <li>
        <%= link_to "Contact Us!", new_contact_path %>
      </li>
    </div>
  

  </header>
  <body class="background">
  <div class="main-body">


    <%= yield %>
  </div>
    <footer>
      <div class="footer-cont">
          <div class="footer-left footer">
            <h2> Contact Us</h2>
              <address class="address">
                100 Rockcrest Dr<br>
                Hammonds Plains, NS<br>
                B4B 1Y6
              </address>
          </div>
            <div class = "footer-middle footer">
              <div id="say-hello">
                <h2> Say Hello </h2>
                <input type="email" placeholder="email"/>
              </div>

            </div>
          <div class="footer-right footer">
            <h2> Social Media </h2>
              <div class="socials">
                <a href="#"><i class='bx bxl-facebook'></i></a>
                <a href="#"><i class='bx bxl-github'></i></a>
                <a href="#"><i class='bx bxl-linkedin'></i></a>
                <a href="#"><i class='bx bxl-youtube'></i></a>
              </div>
          </div>
        
            <div class="copyright footer">
              Created by Nathan Hansford 2024
            </div>
          </div>

    </footer>

  </body>


 
</html>

app/views/pages/index.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
    </head>
    <body>
        <div class="container1">
            <span class="landing-picture">
                <i class="bx bx-edit "></i>
                <p>Find me in app/views/pages/landing.html.erb
                </p>
            </span>

                <p id="cont1-text">
                <strong>Lorem ipsum dolor sit amet,</strong> consectetur adipiscing
                elit. Sed do eiusmod tempor incididunt ut labore et
                dolore magna aliqua. Ut enim ad minim veniam,
                quis nostrud exercitation ullamco laboris nisi ut
                    aliquip ex ea commodo consequat.
                    
                </p>
        </div>
        
        <div class="container2">
        This is the second container for the landing page
        </div>
        <script src="" async defer></script>
    </body>
</html>